@WebApplication6_HostAddress = http://localhost:5222

GET {{WebApplication6_HostAddress}}/todos/
Accept: application/json

###

GET {{WebApplication6_HostAddress}}/todos/1
Accept: application/json

###
